language: android
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-25.0.2
                - android-25
                - extra-google-m2repository
                - extra-android-support
                - extra-android-m2repository
                - extra-google-google_play_services
        licenses:
                - 'android-sdk-preview-license-52d11cd2'
                - 'android-sdk-license-.+'
                - 'google-gdk-license-.+'
script:
        - ./gradlew build
before_install:
  gradle -b wrapper.gradle wrapper
    - mkdir $HOME/.android # For sdkmanager configs
    - echo 'count=0' > $HOME/.android/repositories.cfg # Avoid warning
    - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip
    - mkdir $PWD/android-sdk-linux
    - unzip -qq android-sdk.zip -d $PWD/android-sdk-linux
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle # Remove if you don't need NDK
    - export PATH=$PATH:$ANDROID_HOME/platform-tools/:$ANDROID_NDK_HOME
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools'
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools'
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'build-tools;'$ANDROID_BUILD_TOOLS
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-'$ANDROID_COMPILE_SDK
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;android;m2repository'
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;google_play_services'
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;m2repository'
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'cmake;'$ANDROID_CMAKE_REV
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'ndk-bundle' # Remove if you don't need NDK


branches:
        only:
                - master