language: android
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-25.0.2
                - android-25
                - extra-google-m2repository
                - extra-android-support
                - extra-android-m2repository
                - extra-google-google_play_services
        licenses:
                - 'android-sdk-preview-license-52d11cd2'
                - 'android-sdk-license-.+'
                - 'google-gdk-license-.+'
script:
        - ./gradlew build
before_install:
  gradle -b wrapper.gradle wrapper
branches:
        only:
                - master