language: android
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-25.0.2
                - android-23
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
  gradle -b wrapper.gradle wrapper
branches:
        only:
                - master