language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-25

script:
        - ./gradlew build
before_install:
  gradle -b wrapper.gradle wrapper

branches:
        only:
                - master